// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQkufQWG0csj5rpkfW83tAYpBDbHZWc8',
    appId: '1:330643013308:web:7c76ba4069fbf66313dab9',
    messagingSenderId: '330643013308',
    projectId: 'mafirstclienta',
    authDomain: 'mafirstclienta.firebaseapp.com',
    storageBucket: 'mafirstclienta.firebasestorage.app',
    measurementId: 'G-5704TWW7L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9evo6hNO5IIpbOepTgDfsVjmZ_NtIh58',
    appId: '1:330643013308:android:1e834f670a81b15a13dab9',
    messagingSenderId: '330643013308',
    projectId: 'mafirstclienta',
    storageBucket: 'mafirstclienta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDGsYcMqWt8bFDPXP2Ffgde7qkf8Wtb6Y',
    appId: '1:330643013308:ios:562ca4b13d74004313dab9',
    messagingSenderId: '330643013308',
    projectId: 'mafirstclienta',
    storageBucket: 'mafirstclienta.firebasestorage.app',
    iosClientId: '330643013308-boghsr95uqu0h7kc2kdlh9e56ql4b6uj.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.miniprojet',
  );
}
